query GetSolarPotentialDe($limit: Int, $offset: Int, $search: String, $sort: [String]) {
	solar_potential_de(limit: $limit, offset: $offset, search: $search, sort: $sort) {
		id
		AGS
		ARS
		GEN
		BEZ
		netPotentialShare
		buildingsWithPVShare
		MStRInstalledNetPower
		SolarPotentialInMWhPerYear
		NumberOfBuildingsWithPV
		NumberOfBuildings
	}
}
