name: 'Deploy staging branch'

on:
  push:
    branches:
      - staging

jobs:
  ploi-deploy:
    name: 'Ploi Deploy'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy staging.klimadashboard.at
        uses: Glennmen/ploi-deploy-action@v1.2.0
        with:
          api_token: ${{ secrets.PLOI_API_KEY }}
          server_id: 47649
          site_id: 248307
      - name: Deploy staging.klimadashboard.de
        uses: Glennmen/ploi-deploy-action@v1.2.0
        with:
          api_token: ${{ secrets.PLOI_API_KEY }}
          server_id: 47649
          site_id: 141781
