name: 'Deploy emissions-federal-states branch'

on:
  push:
    branches:
      - feat/de-federal-states-emissions

jobs:
  ploi-deploy:
    name: 'Ploi Deploy'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy staging-federal-states.klimadashboard.at
        uses: Glennmen/ploi-deploy-action@v1.2.0
        with:
          api_token: ${{ secrets.PLOI_API_KEY }}
          server_id: 47649
          site_id: 253022
