name: 'Deploy at-ghg-companies branch'

on:
  push:
    branches:
      - feat/at-ghg-companies

jobs:
  ploi-deploy:
    name: 'Ploi Deploy'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy staging-1.klimadashboard.at
        uses: Glennmen/ploi-deploy-action@v1.2.0
        with:
          api_token: ${{ secrets.PLOI_API_KEY }}
          server_id: 47649
          site_id: 196259
